config/routes.rb
Rails.application.routes.draw do
  resources :surveys, only: [:new, :create]
  root 'surveys#new'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :user_responses, dependent: :destroy
end

app/models/user_response.rb
class UserResponse < ApplicationRecord
  belongs_to :survey
  belongs_to :question
  belongs_to :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    @survey = Survey.first # or find by params if you have multiple surveys
  end

  def create
    survey = Survey.find(params[:survey_id])
    yes_answer_ids = survey.questions.joins(:answers).where(answers: { title: 'Yes' }).pluck('answers.id')

    params[:responses].each do |question_id, answer_id|
      UserResponse.create(survey: survey, question_id: question_id, answer_id: answer_id)
    end

    #********** Calculate current run rating**************
    yes_count = UserResponse.where(survey: survey, answer_id: yes_answer_ids).count
    total_questions = survey.questions.count
    current_rating = (100.0 * yes_count / total_questions).round(2)

    # *****************Calculate average rating***************
    all_responses = UserResponse.where(survey: survey)
    total_yes_answers = all_responses.where(answer_id: yes_answer_ids).count
    total_questions_answered = (all_responses.count.to_f / total_questions).to_f
    average_rating = (100.0 * total_yes_answers / (total_questions_answered * total_questions)).round(2)

    flash[:notice] = "Response submitted! Current rating: #{current_rating}%, Average rating: #{average_rating}%"

    redirect_to new_survey_path
  end
end

app/controllers/user_responses_controller.rb
class UserResponsesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/user_responses_helper.rb
module UserResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/new.html.erb
<div class="container">
  <div class="form-container">
    <h1 class="survey-title"> <%= @survey.title %></h1>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>

    <%= form_with(url: surveys_path, method: :post) do %>
      <% @survey.questions.each_with_index do |question, index| %>
        <div class="question">
          <p class="question-number">Ques <%= index + 1 %></p>
          <p><%= question.title %></p>
          <% question.answers.each do |answer| %>
            <label>
              <%= radio_button_tag "responses[#{question.id}]", answer.id, false %>
              <%= answer.title %>
            </label>
          <% end %>
        </div>
      <% end %>
      <%= hidden_field_tag :survey_id, @survey.id %>
      <%= submit_tag 'Submit', class: 'submit-btn' %>
    <% end %>
  </div>
</div>